version: '3'
services:
  mygogs:
    image: gogs/gogs
    ports:
      - "10080:3000"
      - "10022:22"
    volumes:
      - "${HOME}/gogs:/data"
    depends_on:
      - mysql_db
    links:
      - mysql_db
  mysql_db:
    image: "mysql"
    container_name: "mysql8.0"
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "${HOME}/mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

